definitions:
  wind_inflow:
    properties:
      direction:
        bins: [0., 22.5, 45., 67.5,
               90., 112.5, 135., 157.5,
               180., 202.5, 225., 247.5,
               270., 292.5, 315., 337.5]
      speed:
        default: [9.8, 9.8, 9.8, 9.8, 
                  9.8, 9.8, 9.8, 9.8, 
                  9.8, 9.8, 9.8, 9.8, 
                  9.8, 9.8, 9.8, 9.8]
      probability:
        default: [.025,  .024,  .029,  .036,
                  .063,  .065,  .100,  .122,
                  .063,  .038,  .039,  .083,
                  .213,  .046,  .032,  .022]